### ISSUE TITLE
Error in if (best$ntrees == -1) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by kevinVervier** [nunompmoniz/autoresampling#4]
Sometimes, I get this error `Error in if (best$ntrees == -1) { : missing value where TRUE/FALSE needed`

It happens just after running ATOMIC and printing `Estimating the validation error of model  1 / 20  ...
Estimating the validation error of model  2 / 20  ...
Estimating the validation error of model  3 / 20  ...
Estimating the validation error of model  4 / 20  ...
Estimating the validation error of model  5 / 20  ...
Estimating the validation error of model  6 / 20  ...
Estimating the validation error of model  7 / 20  ...
Estimating the validation error of model  8 / 20  ...
Estimating the validation error of model  9 / 20  ...
Estimating the validation error of model  10 / 20  ...
Estimating the validation error of model  11 / 20  ...
Estimating the validation error of model  12 / 20  ...
Estimating the validation error of model  13 / 20  ...
Estimating the validation error of model  14 / 20  ...
Estimating the validation error of model  15 / 20  ...
Estimating the validation error of model  16 / 20  ...
Estimating the validation error of model  17 / 20  ...
Estimating the validation error of model  18 / 20  ...
Estimating the validation error of model  19 / 20  ...
Estimating the validation error of model  20 / 20  ...`

On the same dataset, it will work, but not on a subset of it (in a cross-validation loop).
I suspect it comes from the lines detecting the best model and the fact that sometimes there is NaN/Nas in `cv.res`.

**Comment by nunompmoniz** [comment]
Hi Kevin!
Indeed, it was due to some NA's being introduced while calculating the metric scores
Someone already noticed that one and the new version should have that solved: https://github.com/nunompmoniz/autoresampling/blob/715da08c8b78af9b909bd22f3fa926550c69a4d8/R/ATOMIC.R#L115
Could you update the version and see if it holds?

**Comment by kevinVervier** [comment]
Perfect. It works now!
